// <auto-generated />
using System;
using System.Collections.Generic;
using Amiki.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amiki.Api.Data.Migrations
{
    [DbContext(typeof(AmikiDb))]
    [Migration("20261006173643_IdeaStatus")]
    partial class IdeaStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amiki.Core.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("After")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("EntityId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Amiki.Modules.Finance.Account", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Name");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Cash",
                            OpeningBalance = 0m
                        },
                        new
                        {
                            Name = "GCash",
                            OpeningBalance = 0m
                        },
                        new
                        {
                            Name = "Maya",
                            OpeningBalance = 0m
                        },
                        new
                        {
                            Name = "Landbank",
                            OpeningBalance = 0m
                        });
                });

            modelBuilder.Entity("Amiki.Modules.Finance.BalanceCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Actual")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid?>("AdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Expected")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("Account", "CheckedAt");

                    b.ToTable("balance_checks", (string)null);
                });

            modelBuilder.Entity("Amiki.Modules.Finance.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "Restaurant",
                            Kind = "Expense",
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "DirectionsCar",
                            Kind = "Expense",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "School",
                            Kind = "Expense",
                            Name = "School"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "PhoneAndroid",
                            Kind = "Expense",
                            Name = "Load & data"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "ReceiptLong",
                            Kind = "Expense",
                            Name = "Bills"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "ShoppingBag",
                            Kind = "Expense",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000007"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "LocalHospital",
                            Kind = "Expense",
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "SportsEsports",
                            Kind = "Expense",
                            Name = "Fun"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000009"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "Toll",
                            Kind = "Expense",
                            Name = "Fees"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-00000000000a"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "MoreHoriz",
                            Kind = "Expense",
                            Name = "Other"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-00000000000b"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "FactCheck",
                            Kind = "Expense",
                            Name = "Balance fix"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000101"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "Savings",
                            Kind = "Income",
                            Name = "Allowance"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000102"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "Work",
                            Kind = "Income",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000103"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "CardGiftcard",
                            Kind = "Income",
                            Name = "Gift"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000104"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "Replay",
                            Kind = "Income",
                            Name = "Refund"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000105"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "AttachMoney",
                            Kind = "Income",
                            Name = "Other income"
                        },
                        new
                        {
                            Id = new Guid("1f0c8a01-0000-4000-8000-000000000106"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "FactCheck",
                            Kind = "Income",
                            Name = "Balance fix"
                        });
                });

            modelBuilder.Entity("Amiki.Modules.Finance.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StartBalance")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Amiki.Modules.Finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Amiki.Modules.Finance.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Fee")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("Amiki.Modules.Ideas.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ideas", (string)null);
                });

            modelBuilder.Entity("Amiki.Modules.Inbox.InboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("inbox_items", (string)null);
                });

            modelBuilder.Entity("Amiki.Modules.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Due")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
